[supervisord]
nodaemon=true
# Пишем логи самого супервизора в стандартный вывод
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/redis/supervisord.pid

[program:redis]
command=redis-server --port 6379 --protected-mode no --daemonize no
autostart=true
autorestart=true
# Перенаправляем логи редиса в консоль
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:backend]
command=python run.py
directory=/app
autostart=true
autorestart=true
# Самое важное: логи бэкенда в консоль!
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0