[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/var/run/redis/supervisord.pid

[program:redis]
# Запускаем redis на порту 6379 в фоне самого контейнера
command=redis-server --port 6379 --protected-mode no --daemonize no
autostart=true
autorestart=true
stdout_logfile=/app/logs/redis.log
stderr_logfile=/app/logs/redis_err.log

[program:backend]
command=python run.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/backend.log
stderr_logfile=/app/logs/backend_err.log