/* =====================================================
   SQLCRAFT — main.js
   Mock frontend logic (no backend yet).
   All API calls are stubbed with setTimeout / fake data.
   ===================================================== */

/* ── CONFIG ─────────────────────────────────────────────── */
const API_BASE = '/api/v1';            // будущий бэкенд
const MOCK = true;                     // true → использовать моки

/* ── MOCK DATA ──────────────────────────────────────────── */
const MOCK_SQL_TEMPLATES = {
  'postgresql': `-- Generated by SQLCraft
SELECT
  u.id,
  u.name,
  u.email,
  COUNT(o.id)       AS total_orders,
  SUM(o.total)      AS revenue
FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE u.created_at >= NOW() - INTERVAL '30 days'
  AND u.is_active = true
GROUP BY u.id, u.name, u.email
ORDER BY revenue DESC
LIMIT 50;`,
  'mysql': `-- Generated by SQLCraft
SELECT
  u.id,
  u.name,
  u.email,
  COUNT(o.id)       AS total_orders,
  SUM(o.total)      AS revenue
FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE u.created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
  AND u.is_active = 1
GROUP BY u.id, u.name, u.email
ORDER BY revenue DESC
LIMIT 50;`,
  'sqlite': `-- Generated by SQLCraft
SELECT
  u.id,
  u.name,
  u.email,
  COUNT(o.id)       AS total_orders,
  SUM(o.total)      AS revenue
FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE u.created_at >= datetime('now', '-30 days')
  AND u.is_active = 1
GROUP BY u.id, u.name, u.email
ORDER BY revenue DESC
LIMIT 50;`,
};

const MOCK_RESULTS = {
  columns: ['id', 'name', 'email', 'total_orders', 'revenue'],
  rows: [
    [1,  'Alice Johnson',  'alice@example.com',   24, '$4,320.00'],
    [2,  'Bob Smith',      'bob@example.com',     18, '$2,890.50'],
    [3,  'Carol White',    'carol@example.com',   31, '$6,100.00'],
    [4,  'David Brown',    'david@example.com',    7,  '$890.25'],
    [5,  'Eva Martinez',   'eva@example.com',     12, '$1,540.00'],
    [6,  'Frank Wilson',   'frank@example.com',   null, null],
  ],
  rowCount: 6,
  execMs: 34,
};

const MOCK_DB_TABLES = [
  { name: 'users',    rows: '12,483' },
  { name: 'orders',   rows: '89,210' },
  { name: 'products', rows: '3,541'  },
  { name: 'sessions', rows: '204,7k' },
  { name: 'payments', rows: '67,891' },
];

const MOCK_HISTORY = [
  { query: 'Топ-10 клиентов по выручке за месяц', time: '2 мин назад' },
  { query: 'Незавершённые заказы старше 7 дней',   time: '18 мин назад' },
  { query: 'Средний чек по категориям товаров',    time: '1 ч назад' },
  { query: 'Пользователи без заказов (last 90d)',  time: '3 ч назад' },
];

/* ── UTILS ──────────────────────────────────────────────── */
function delay(ms) { return new Promise(r => setTimeout(r, ms)); }

function showToast(msg, type = 'info') {
  const container = document.getElementById('toast-container');
  if (!container) return;
  const icons = { success: '✓', error: '✕', info: 'ℹ' };
  const toast = document.createElement('div');
  toast.className = `toast ${type}`;
  toast.innerHTML = `<span>${icons[type] || 'ℹ'}</span><span>${msg}</span>`;
  container.appendChild(toast);
  setTimeout(() => toast.remove(), 3500);
}

function copyToClipboard(text) {
  navigator.clipboard.writeText(text).then(() => showToast('Скопировано в буфер', 'success'));
}

/* ── API LAYER (stub) ───────────────────────────────────── */
const api = {
  async generateSQL(prompt, dialect) {
    if (MOCK) {
      await delay(900 + Math.random() * 600);
      return MOCK_SQL_TEMPLATES[dialect] || MOCK_SQL_TEMPLATES['postgresql'];
    }
    const res = await fetch(`${API_BASE}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${auth.getToken()}` },
      body: JSON.stringify({ prompt, dialect }),
    });
    if (!res.ok) throw new Error(await res.text());
    const data = await res.json();
    return data.sql;
  },

  async executeSQL(sql, dialect) {
    if (MOCK) {
      await delay(600 + Math.random() * 400);
      if (Math.random() < 0.1) throw new Error('connection refused: database unreachable');
      return MOCK_RESULTS;
    }
    const res = await fetch(`${API_BASE}/execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${auth.getToken()}` },
      body: JSON.stringify({ sql, dialect }),
    });
    if (!res.ok) throw new Error(await res.text());
    return res.json();
  },

  async connectDB(config) {
    if (MOCK) {
      await delay(1200);
      return { success: true, tables: MOCK_DB_TABLES };
    }
    const res = await fetch(`${API_BASE}/db/connect`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${auth.getToken()}` },
      body: JSON.stringify(config),
    });
    if (!res.ok) throw new Error(await res.text());
    return res.json();
  },

async login(email, password) {
    const res = await fetch(`/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    if (!res.ok) {
      const status = res.status;
      if (status === 400) throw { type: 'error', msg: 'Неверный email или пароль' };
      if (status === 500) throw { type: 'error', msg: 'Ошибка сервера. Попробуйте позже' };
      throw { type: 'error', msg: 'Неизвестная ошибка' };
    }
    const data = await res.json();
    return { token: data.jwt_token, user: { id: data.id, name: data.name, email: data.email, plan: data.plan } };
  },

  async register(name, email, password) {
    const res = await fetch(`/auth/signup`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name, email, password }),
    });
    if (!res.ok) {
      const status = res.status;
      if (status === 401) throw { type: 'error', msg: 'Неверный email или пароль' };
      if (status === 403) throw { type: 'error', msg: 'Доступ запрещён' };
      if (status === 500) throw { type: 'error', msg: 'Ошибка сервера. Попробуйте позже' };
      throw { type: 'error', msg: 'Неизвестная ошибка' };
    }
    const data = await res.json();
    return { token: data.jwt_token, user: { id: data.id, name: data.name, email: data.email, plan: data.plan } };
  },
};

/* ── AUTH MODULE ────────────────────────────────────────── */
const auth = {
  getToken() { return localStorage.getItem('sqlcraft_token'); },
  getUser()  {
    try { return JSON.parse(localStorage.getItem('sqlcraft_user') || 'null'); }
    catch { return null; }
  },
  setSession(token, user) {
    localStorage.setItem('sqlcraft_token', token);
    localStorage.setItem('sqlcraft_user', JSON.stringify(user));
  },
  logout() {
    localStorage.removeItem('sqlcraft_token');
    localStorage.removeItem('sqlcraft_user');
    window.location.href = 'index.html';
  },
  // Проверяем exp прямо из JWT payload — без запроса к серверу
  isLoggedIn() {
    const token = this.getToken();
    if (!token) return false;
    try {
      const payload = JSON.parse(atob(token.split('.')[1]));
      return payload.exp * 1000 > Date.now();
    } catch {
      return false;
    }
  },
  requireAuth() {
    if (!this.isLoggedIn()) {
      this.logout(); // чистим протухшие данные
      return false;
    }
    return true;
  },
};

/* ── DIALECT SELECTOR ───────────────────────────────────── */
class DialectSelector {
  constructor(btnEl, dropEl) {
    this.btn = btnEl;
    this.drop = dropEl;
    this.value = 'postgresql';
    this._setupEvents();
  }
  _setupEvents() {
    this.btn.addEventListener('click', (e) => { e.stopPropagation(); this._toggle(); });
    document.addEventListener('click', () => this._close());
    this.drop.querySelectorAll('.dialect-option').forEach(opt => {
      opt.addEventListener('click', (e) => {
        e.stopPropagation();
        this.value = opt.dataset.value;
        this.btn.querySelector('.dialect-current').textContent = opt.dataset.label;
        this.drop.querySelectorAll('.dialect-option').forEach(o => o.classList.remove('active'));
        opt.classList.add('active');
        this._close();
      });
    });
  }
  _toggle() { this.btn.classList.toggle('open'); this.drop.classList.toggle('open'); }
  _close()  { this.btn.classList.remove('open'); this.drop.classList.remove('open'); }
}

/* ── EXPORT UTILS ───────────────────────────────────────── */
const exportUtils = {
  toCSV(results) {
    const header = results.columns.join(',');
    const rows = results.rows.map(r => r.map(v => v === null ? '' : `"${v}"`).join(','));
    return [header, ...rows].join('\n');
  },
  toJSON(results) {
    const arr = results.rows.map(r => {
      const obj = {};
      results.columns.forEach((c, i) => { obj[c] = r[i]; });
      return obj;
    });
    return JSON.stringify(arr, null, 2);
  },
  download(filename, content, mime) {
    const blob = new Blob([content], { type: mime });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
  },
};

/* ── SQL HIGHLIGHTER (simple) ───────────────────────────── */
function highlightSQL(sql) {
  const keywords = ['SELECT','FROM','WHERE','JOIN','LEFT','RIGHT','INNER','OUTER',
    'ON','GROUP','BY','ORDER','HAVING','LIMIT','OFFSET','INSERT','UPDATE','DELETE',
    'INTO','VALUES','SET','CREATE','TABLE','ALTER','DROP','INDEX','AND','OR','NOT',
    'IN','IS','NULL','AS','DISTINCT','COUNT','SUM','AVG','MIN','MAX','CASE','WHEN',
    'THEN','ELSE','END','WITH','UNION','ALL','INTERVAL','DATE_SUB','NOW','datetime'];
  let out = sql
    .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  // strings
  out = out.replace(/'[^']*'/g, m => `<span class="sql-str">${m}</span>`);
  // comments
  out = out.replace(/(--[^\n]*)/g, `<span class="sql-cmt">$1</span>`);
  // keywords
  const kwRe = new RegExp(`\\b(${keywords.join('|')})\\b`, 'g');
  out = out.replace(kwRe, `<span class="sql-kw">$1</span>`);
  // numbers
  out = out.replace(/\b(\d+)\b/g, `<span class="sql-num">$1</span>`);
  return out;
}

/* ── WORKSHOP PAGE INIT ─────────────────────────────────── */
function initWorkshop() {
  if (!document.getElementById('workshop-page')) return;
  if (!auth.requireAuth()) return;

  // User name
  const user = auth.getUser();
  const userNameEl = document.getElementById('user-name');
  if (userNameEl && user) userNameEl.textContent = user.name || user.email;

  let currentSQL = '';
  let lastResults = null;
  let executeEnabled = false;

  // Multi-DB state
  const connectedDBs = [];   // [{ id, name, host, tables, active }]
  let activeDBId = null;

  function hasActiveDB() { return activeDBId !== null; }
  function getActiveDB() { return connectedDBs.find(d => d.id === activeDBId) || null; }

  // Dialect
  const dialectBtn  = document.getElementById('dialect-btn');
  const dialectDrop = document.getElementById('dialect-dropdown');
  const dialect = dialectBtn && dialectDrop ? new DialectSelector(dialectBtn, dialectDrop) : null;

  // History
  renderHistory();

  // DB Connect btn
  const dbConnectBtn = document.getElementById('db-connect-btn');
  if (dbConnectBtn) {
    dbConnectBtn.addEventListener('click', () => openDBModal());
  }

  // Generate
  const generateBtn = document.getElementById('generate-btn');
  const promptTextarea = document.getElementById('prompt-textarea');
  if (generateBtn && promptTextarea) {
    generateBtn.addEventListener('click', handleGenerate);
    promptTextarea.addEventListener('keydown', (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') handleGenerate();
    });
  }

  async function handleGenerate() {
    const prompt = promptTextarea.value.trim();
    if (!prompt) { showToast('Введите запрос', 'error'); return; }

    setGenerating(true);
    try {
      const sql = await api.generateSQL(prompt, dialect ? dialect.value : 'postgresql');
      currentSQL = sql;
      renderSQL(sql);
      addHistoryItem(prompt);
      showToast('SQL сгенерирован', 'success');

      // Auto-execute if enabled
      if (executeEnabled && hasActiveDB()) {
        await handleExecute();
      }
    } catch (err) {
      showToast(`Ошибка: ${err.message}`, 'error');
    } finally {
      setGenerating(false);
    }
  }

  function setGenerating(v) {
    if (!generateBtn) return;
    generateBtn.disabled = v;
    generateBtn.innerHTML = v
      ? '<span class="spin-icon">◌</span> Генерация...'
      : '⚡ Генерировать SQL';
    if (v) {
      const spin = generateBtn.querySelector('.spin-icon');
      if (spin) spin.style.animation = 'spin 1s linear infinite';
    }
  }

  function renderSQL(sql) {
    const body = document.getElementById('sql-output-body');
    if (!body) return;
    body.innerHTML = highlightSQL(sql);
    syncExecBtn();
  }

  // Execute manually


  // Copy SQL
  const copyBtn = document.getElementById('copy-sql-btn');
  if (copyBtn) copyBtn.addEventListener('click', () => {
    if (currentSQL) copyToClipboard(currentSQL);
    else showToast('Нет SQL для копирования', 'error');
  });

  // Execute toggle
  const executeToggle = document.getElementById('execute-toggle');
  const resultsSection = document.getElementById('results-section');
  const executeSection = document.getElementById('execute-section');
  const execBtn = document.getElementById('exec-sql-btn');  
  if (execBtn) execBtn.addEventListener('click', handleExecute);
  function syncExecBtn() {
    if (!execBtn) return;
    // кнопка «Выполнить» видна только когда: есть SQL + галочка включена
    const show = executeEnabled && currentSQL.length > 0;
    execBtn.style.display = show ? 'inline-flex' : 'none';
  }

  if (executeToggle) {
    executeToggle.addEventListener('change', () => {
      executeEnabled = executeToggle.checked;
      if (resultsSection) {
        resultsSection.style.display = executeEnabled ? 'block' : 'none';
      }
      syncExecBtn();
    });
  }

  async function handleExecute() {
    if (!currentSQL) { showToast('Сначала сгенерируйте SQL', 'error'); return; }
    if (!hasActiveDB()) { showToast('Подключите базу данных', 'error'); return; }

    if (execBtn) { execBtn.disabled = true; execBtn.textContent = '▶ Выполнение...'; }
    try {
      const results = await api.executeSQL(currentSQL, dialect ? dialect.value : 'postgresql');
      lastResults = results;
      renderResults(results);
      showToast(`Получено ${results.rowCount} строк за ${results.execMs}ms`, 'success');
    } catch (err) {
      showToast(`Ошибка выполнения: ${err.message}`, 'error');
    } finally {
      if (execBtn) { execBtn.disabled = false; execBtn.textContent = '▶ Выполнить'; }
    }
  }

  function renderResults(results) {
    const tbody = document.getElementById('results-tbody');
    const thead = document.getElementById('results-thead');
    const footer = document.getElementById('results-footer-info');
    if (!tbody || !thead) return;

    thead.innerHTML = results.columns.map(c => `<th>${c}</th>`).join('');
    tbody.innerHTML = results.rows.map(row =>
      `<tr>${row.map(v => `<td class="${v === null ? 'null-val' : ''}">${v === null ? 'NULL' : v}</td>`).join('')}</tr>`
    ).join('');
    if (footer) footer.textContent = `${results.rowCount} строк • ${results.execMs}ms`;
  }

  // Export buttons
  document.getElementById('export-csv')?.addEventListener('click', () => {
    if (!lastResults) return showToast('Нет данных для экспорта', 'error');
    exportUtils.download('results.csv', exportUtils.toCSV(lastResults), 'text/csv');
    showToast('CSV экспортирован', 'success');
  });
  document.getElementById('export-json')?.addEventListener('click', () => {
    if (!lastResults) return showToast('Нет данных для экспорта', 'error');
    exportUtils.download('results.json', exportUtils.toJSON(lastResults), 'application/json');
    showToast('JSON экспортирован', 'success');
  });
  document.getElementById('export-sql')?.addEventListener('click', () => {
    if (!currentSQL) return showToast('Нет SQL для экспорта', 'error');
    exportUtils.download('query.sql', currentSQL, 'text/plain');
    showToast('SQL файл скачан', 'success');
  });

  // History
  function addHistoryItem(query) {
    MOCK_HISTORY.unshift({ query, time: 'только что' });
    renderHistory();
  }
  function renderHistory() {
    const container = document.getElementById('history-list');
    if (!container) return;
    container.innerHTML = MOCK_HISTORY.map((h, i) => `
      <div class="history-item ${i === 0 ? 'active' : ''}" onclick="selectHistory(${i})">
        <div class="history-item-query">${h.query}</div>
        <div class="history-item-time">${h.time}</div>
      </div>
    `).join('');
  }
  window.selectHistory = function(i) {
    if (promptTextarea) promptTextarea.value = MOCK_HISTORY[i].query;
    document.querySelectorAll('.history-item').forEach((el, j) => el.classList.toggle('active', j === i));
  };

  // DB Modal
  const dbModal = document.getElementById('db-modal');
  window.openDBModal = function() {
    if (dbModal) dbModal.classList.add('open');
  };
  window.closeDBModal = function() {
    if (dbModal) dbModal.classList.remove('open');
  };
  dbModal?.querySelector('.modal-overlay')?.addEventListener('click', (e) => {
    if (e.target === e.currentTarget) closeDBModal();
  });

  const dbConnectSubmitBtn = document.getElementById('db-connect-submit');
  if (dbConnectSubmitBtn) {
    dbConnectSubmitBtn.addEventListener('click', async () => {
      dbConnectSubmitBtn.disabled = true;
      dbConnectSubmitBtn.textContent = 'Подключение...';
      try {
        const dbName = document.getElementById('db-name')?.value || 'mydb';
        const host   = document.getElementById('db-host')?.value || 'localhost';
        const config = {
          host,
          port:     document.getElementById('db-port')?.value || '5432',
          dbname:   dbName,
          user:     document.getElementById('db-user')?.value || 'postgres',
          password: document.getElementById('db-pass')?.value || '',
        };
        const result = await api.connectDB(config);

        // Add to list
        const id = Date.now();
        connectedDBs.push({ id, name: dbName, host, tables: result.tables });
        // Set active to this new one
        activeDBId = id;

        renderDBList();
        closeDBModal();
        showToast(`БД «${dbName}» подключена!`, 'success');

        // Show execute section now that we have at least one DB
        if (executeSection) executeSection.style.display = 'block';
      } catch (err) {
        showToast(`Ошибка подключения: ${err.message}`, 'error');
      } finally {
        dbConnectSubmitBtn.disabled = false;
        dbConnectSubmitBtn.textContent = 'Подключить';
      }
    });
  }

  function renderDBList() {
    const list = document.getElementById('db-list');
    if (!list) return;

    if (connectedDBs.length === 0) {
      list.innerHTML = `<div style="font-size:12px; font-family:var(--font-mono); color:var(--text-dim); padding: 6px 2px;">Нет подключений</div>`;
      return;
    }

    list.innerHTML = connectedDBs.map(db => `
      <div class="db-entry ${db.id === activeDBId ? 'db-entry-active' : ''}"
           onclick="selectDB(${db.id})"
           style="
             border-radius: 6px;
             border: 1px solid ${db.id === activeDBId ? 'var(--border-hi)' : 'transparent'};
             background: ${db.id === activeDBId ? 'var(--bg-hover)' : 'transparent'};
             margin-bottom: 4px; cursor: pointer; transition: all 0.15s;
           ">
        <div style="display:flex; align-items:center; gap:8px; padding: 8px 10px;">
          <span class="status-dot online" style="width:6px;height:6px; flex-shrink:0;"></span>
          <span style="font-size:12px; font-family:var(--font-mono); font-weight:700; color:var(--text); flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">${db.name}</span>
          <button onclick="event.stopPropagation(); disconnectDB(${db.id})"
            style="background:none; border:none; color:var(--text-dim); cursor:pointer; font-size:13px; padding:0 2px; line-height:1; transition:color 0.15s;"
            title="Отключить"
            onmouseover="this.style.color='#ff6b6b'"
            onmouseout="this.style.color='var(--text-dim)'">✕</button>
        </div>
        ${db.id === activeDBId ? `
        <div class="db-tables" style="padding: 0 10px 8px;">
          ${db.tables.map(t => `
            <div class="db-table-item">
              <span class="table-icon">⊞</span>
              <span>${t.name}</span>
              <span class="row-count">${t.rows}</span>
            </div>
          `).join('')}
        </div>` : ''}
      </div>
    `).join('');
  }

  window.selectDB = function(id) {
    activeDBId = id;
    renderDBList();
  };

  window.disconnectDB = function(id) {
    const idx = connectedDBs.findIndex(d => d.id === id);
    if (idx === -1) return;
    const name = connectedDBs[idx].name;
    connectedDBs.splice(idx, 1);

    if (activeDBId === id) {
      activeDBId = connectedDBs.length > 0 ? connectedDBs[connectedDBs.length - 1].id : null;
    }
    renderDBList();

    // Hide execute section if no DBs left
    if (connectedDBs.length === 0 && executeSection) {
      executeSection.style.display = 'none';
      if (executeToggle) executeToggle.checked = false;
      executeEnabled = false;
      if (resultsSection) resultsSection.style.display = 'none';
      syncExecBtn();
    }
    showToast(`БД «${name}» отключена`, 'info');
  };

  // Logout
  document.getElementById('logout-btn')?.addEventListener('click', () => {
    auth.logout();
  });
}

/* ── AUTH PAGE INIT ─────────────────────────────────────── */
function initAuth() {
  if (!document.getElementById('auth-page')) return;
  if (auth.isLoggedIn()) { window.location.href = 'workshop.html'; return; }

  // Tabs
  const tabs = document.querySelectorAll('.auth-tab');
  const panels = document.querySelectorAll('.auth-form-panel');
  tabs.forEach(tab => {
    tab.addEventListener('click', () => {
      tabs.forEach(t => t.classList.remove('active'));
      panels.forEach(p => p.classList.remove('active'));
      tab.classList.add('active');
      document.getElementById(tab.dataset.panel)?.classList.add('active');
    });
  });

  // Login
  document.getElementById('login-btn')?.addEventListener('click', async () => {
    const email = document.getElementById('login-email')?.value?.trim();
    const pass  = document.getElementById('login-pass')?.value;
    if (!email || !pass) return showAlert('login', 'Заполните все поля');
    const btn = document.getElementById('login-btn');
    btn.disabled = true; btn.textContent = 'Вход...';
    clearAlert('login');
    try {
      const { token, user } = await api.login(email, pass);
      auth.setSession(token, user);
      window.location.href = 'workshop.html';
    } catch (err) {
      showAlert('login', err.msg || 'Неизвестная ошибка');
    } finally {
      btn.disabled = false; btn.textContent = 'Войти';
    }
  });

  // Register
  document.getElementById('register-btn')?.addEventListener('click', async () => {
    const name  = document.getElementById('reg-name')?.value?.trim();
    const email = document.getElementById('reg-email')?.value?.trim();
    const pass  = document.getElementById('reg-pass')?.value;
    if (!name || !email || !pass) return showAlert('register', 'Заполните все поля');
    if (pass.length < 8) return showAlert('register', 'Пароль должен быть минимум 8 символов');
    const btn = document.getElementById('register-btn');
    btn.disabled = true; btn.textContent = 'Регистрация...';
    clearAlert('register');
    try {
      const { token, user } = await api.register(name, email, pass);
      auth.setSession(token, user);
      window.location.href = 'workshop.html';
    } catch (err) {
      showAlert('register', err.msg || 'Неизвестная ошибка');
    } finally {
      btn.disabled = false; btn.textContent = 'Создать аккаунт';
    }
});
}

/* ── INDEX PAGE INIT ────────────────────────────────────── */
function initIndex() {
  if (!document.getElementById('index-page')) return;
  // Typing effect in hero
  const cursor = document.getElementById('hero-cursor');
  if (cursor) {
    const texts = [
      'Покажи топ-10 клиентов по выручке за этот месяц',
      'Найди незавершённые заказы старше 7 дней',
      'Средний чек по категориям товаров',
    ];
    let ti = 0, ci = 0, deleting = false;
    const targetEl = document.getElementById('hero-typing');
    if (targetEl) {
      function type() {
        const text = texts[ti];
        if (!deleting) {
          targetEl.textContent = text.slice(0, ++ci);
          if (ci === text.length) { deleting = true; setTimeout(type, 1800); return; }
        } else {
          targetEl.textContent = text.slice(0, --ci);
          if (ci === 0) { deleting = false; ti = (ti + 1) % texts.length; }
        }
        setTimeout(type, deleting ? 30 : 55);
      }
      setTimeout(type, 600);
    }
  }

  // CTA buttons redirect
  document.querySelectorAll('[data-goto]').forEach(el => {
    el.addEventListener('click', () => window.location.href = el.dataset.goto);
  });
}

/* ── BOOT ───────────────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', () => {
  initIndex();
  initAuth();
  initWorkshop();
});

function showAlert(form, msg) {
    const id = form === 'login' ? 'alert-login' : 'alert-register';
    let el = document.getElementById(id);
    if (!el) {
      el = document.createElement('div');
      el.id = id;
      el.className = 'auth-alert';
      const btn = document.getElementById(form === 'login' ? 'login-btn' : 'register-btn');
      btn?.parentNode.insertBefore(el, btn);
    }
    el.textContent = msg;
    el.style.display = 'flex';
  }

  function clearAlert(form) {
    const id = form === 'login' ? 'alert-login' : 'alert-register';
    const el = document.getElementById(id);
    if (el) el.style.display = 'none';
  }
